const PLACEHOLDER_FIELD_ID: string = "__PLACEHOLDER__" as const;
const FORM_STRUCTURE_DROPPABLE_ID: string = "__FORM_STRUCTURE__" as const;

export { FORM_STRUCTURE_DROPPABLE_ID, PLACEHOLDER_FIELD_ID };
