export const MRT_Localization_Hebrew = {
  actions: "פעולות",
  and: "וגם",
  cancel: "ביטול",
  changeFilterMode: "שנה מוד פילטר",
  changeSearchMode: "שנה מוד חיפוש",
  clearFilter: "נקה פילטר",
  clearSearch: "נקה חיפוש",
  clearSort: "נקה מיון",
  clickToCopy: "לחץ להעתיק",
  collapse: "כיווץ",
  collapseAll: "כיווץ הכל",
  columnActions: "פעולות עמודה",
  copiedToClipboard: "הועתק ללוח",
  dropToGroupBy: "זרוק כאן לקבץ לפי {column}",
  edit: "עריכה",
  expand: "הרחבה",
  expandAll: "הרחב הכל",
  filterArrIncludes: "מכיל",
  filterArrIncludesAll: "מכיל הכל",
  filterArrIncludesSome: "כולל",
  filterBetween: "בין לבין",
  filterBetweenInclusive: "בין לבין כולל",
  filterByColumn: "סינון לפי {column}",
  filterContains: "מכיל",
  filterEmpty: "ריק",
  filterEndsWith: "נגמר ב",
  filterEquals: "שווה",
  filterEqualsString: "שווה",
  filterFuzzy: "מְעוּרפָּל",
  filterGreaterThan: "גדול מ",
  filterGreaterThanOrEqualTo: "גדול או שווה",
  filterInNumberRange: "בין לבין",
  filterIncludesString: "מכיל",
  filterIncludesStringSensitive: "מכיל",
  filterLessThan: "פחות מ",
  filterLessThanOrEqualTo: "פחות או שווה",
  filterMode: "מוד פילטר: {filterType}",
  filterNotEmpty: "לא ריק",
  filterNotEquals: "לא שווה",
  filterStartsWith: "מתחיל ב",
  filterWeakEquals: "שווה",
  filteringByColumn: "פילטור לפי {column} - {filterType} {filterValue}",
  goToFirstPage: "לעמוד הראשון",
  goToLastPage: "לעמוד האחרון",
  goToNextPage: "לעמוד הבא",
  goToPreviousPage: "לעמוד הקודם",
  grab: "תפוס",
  groupByColumn: "קבץ לפי {column}",
  groupedBy: "קובץ לפי",
  hideAll: "הסתר הכל",
  hideColumn: "הסתר את עמודה {column}",
  max: "מקסימום",
  min: "מינימום",
  move: "הזזה",
  noRecordsToDisplay: "אין מידע להציג",
  noResultsFound: "לא נמצאו תוצאות",
  of: "מתוך",
  or: "or",
  pin: "הצמד",
  pinToLeft: "הצמד לשמאל",
  pinToRight: "הצמד לימין",
  resetColumnSize: "אפס את גודל העמודה",
  resetOrder: "אפס סדר",
  rowActions: "פעולות שורה",
  rowNumber: "#",
  rowNumbers: "מספרי שורות",
  rowsPerPage: "שורות בעמוד",
  save: "שמירה",
  search: "חיפוש",
  selectedCountOfRowCountRowsSelected: "נבחרו {selectedCount} מתוך {rowCount} עמוד(ות)",
  select: "בחר",
  showAll: "הצג הכל",
  showAllColumns: "הצג את כל העמודות",
  showHideColumns: "הצג/הסתר עמודות",
  showHideFilters: "הצג/הסתר סינון",
  showHideSearch: "הצג/הסתר חיפוש",
  sortByColumnAsc: "מיון לפי {column} בסדר עולה (א-ת)",
  sortByColumnDesc: "מיון לפי {column} בסדר יורד (ת-א)",
  sortedByColumnAsc: "מוין לפי {column} בסדר עולה (א-ת)",
  sortedByColumnDesc: "מוין לפי {column} בסדר יורד (ת-א)",
  thenBy: ", then by ",
  toggleDensity: "החלף צפיפות",
  toggleFullScreen: "החלף מסך מלא",
  toggleSelectAll: "החלף בחר הכל",
  toggleSelectRow: "החלף בחירת שורה",
  selectRow: "בחר שורה",
  unSelectRow: "בטל בחירת שורה",
  toggleVisibility: "החלף נראות",
  ungroupByColumn: "בטל קיבוץ לפי {column}",
  unpin: "Unpin",
  unpinAll: "Unpin all",
};
