export const MRT_Localization_Hebrew = {
  actions: "פעולות",
  and: "וגם",
  cancel: "ביטול",
  changeFilterMode: "שינוי מצב סינון",
  changeSearchMode: "שינוי מצב חיפוש",
  clearFilter: "ניקוי סינון",
  clearSearch: "ניקוי חיפוש",
  clearSort: "ניקוי מיון",
  clickToCopy: "לחיצה להעתקה",
  collapse: "כיווץ",
  collapseAll: "כיווץ הכל",
  columnActions: "פעולות עמודה",
  copiedToClipboard: "הועתק ללוח",
  dropToGroupBy: "גרירה לכאן לקיבוץ לפי {column}",
  edit: "עריכה",
  expand: "הרחבה",
  expandAll: "הרחבת הכל",
  filterArrIncludes: "מכיל",
  filterArrIncludesAll: "מכיל הכל",
  filterArrIncludesSome: "כולל",
  filterBetween: "בין לבין",
  filterBetweenInclusive: "בין לבין כולל",
  filterByColumn: "סינון לפי {column}",
  filterContains: "מכיל",
  filterEmpty: "ריק",
  filterEndsWith: "נגמר ב",
  filterEquals: "שווה",
  filterEqualsString: "שווה",
  filterFuzzy: "מְעוּרפָּל",
  filterGreaterThan: "גדול מ",
  filterGreaterThanOrEqualTo: "גדול או שווה",
  filterInNumberRange: "בין לבין",
  filterIncludesString: "מכיל",
  filterIncludesStringSensitive: "מכיל",
  filterLessThan: "פחות מ",
  filterLessThanOrEqualTo: "פחות או שווה",
  filterMode: "מוד פילטר: {filterType}",
  filterNotEmpty: "לא ריק",
  filterNotEquals: "לא שווה",
  filterStartsWith: "מתחיל ב",
  filterWeakEquals: "שווה",
  filteringByColumn: "פילטור לפי {column} - {filterType} {filterValue}",
  goToFirstPage: "לעמוד הראשון",
  goToLastPage: "לעמוד האחרון",
  goToNextPage: "לעמוד הבא",
  goToPreviousPage: "לעמוד הקודם",
  grab: "אחיזה",
  groupByColumn: "קיבוץ לפי {column}",
  groupedBy: "קובץ לפי",
  hideAll: "הסתרת הכל",
  hideColumn: "הסתרת עמודה {column}",
  max: "מקסימום",
  min: "מינימום",
  move: "הזזה",
  noRecordsToDisplay: "אין מידע להציג",
  noResultsFound: "לא נמצאו תוצאות",
  of: "מתוך",
  or: "or",
  pin: "הצמדה",
  pinToLeft: "הצמדה לשמאל",
  pinToRight: "הצמדה לימין",
  resetColumnSize: "איפוס גודל העמודה",
  resetOrder: "איפוס סדר",
  rowActions: "פעולות שורה",
  rowNumber: "#",
  rowNumbers: "מספרי שורות",
  rowsPerPage: "שורות בעמוד",
  save: "שמירה",
  search: "חיפוש",
  selectedCountOfRowCountRowsSelected: "נבחרו {selectedCount} מתוך {rowCount} עמוד(ות)",
  select: "בחירה",
  showAll: "הצגת הכל",
  showAllColumns: "הצגת כל העמודות",
  showHideColumns: "הצגה/הסתרת עמודות",
  showHideFilters: "הצגה/הסתרת סינון",
  showHideSearch: "הצגה/הסתרת חיפוש",
  sortByColumnAsc: "מיון לפי {column} בסדר עולה (א-ת)",
  sortByColumnDesc: "מיון לפי {column} בסדר יורד (ת-א)",
  sortedByColumnAsc: "מוין לפי {column} בסדר עולה (א-ת)",
  sortedByColumnDesc: "מוין לפי {column} בסדר יורד (ת-א)",
  thenBy: ", then by ",
  toggleDensity: "החלפת צפיפות",
  toggleFullScreen: "החלפת מסך מלא",
  toggleSelectAll: "החלפת בחר הכל",
  toggleSelectRow: "החלפת בחירת שורה",
  selectRow: "בחירת שורה",
  unSelectRow: "ביטול בחירת שורה",
  toggleVisibility: "החלפת נראות",
  ungroupByColumn: "ביטול קיבוץ לפי {column}",
  unpin: "Unpin",
  unpinAll: "Unpin all",
};
