import * as MuiIcons from "@mui/icons-material";
import { formIcon } from "formula-gear";

export const DEFAULT_ICON_NAME = formIcon.GridView;

export const formIconsNamesMap = new Map<string | number, any>([
  [formIcon.GridView, MuiIcons.GridViewOutlined],
  [formIcon.CropSquare, MuiIcons.CropSquareOutlined],
  [formIcon.Description, MuiIcons.DescriptionOutlined],
  [formIcon.TableChart, MuiIcons.TableChartOutlined],
  [formIcon.DynamicForm, MuiIcons.DynamicFormOutlined],
  [formIcon.Dataset, MuiIcons.DatasetOutlined],
  [formIcon.Article, MuiIcons.ArticleOutlined],
  [formIcon.FolderOpen, MuiIcons.FolderOpenOutlined],
  [formIcon.CloudUpload, MuiIcons.CloudUploadOutlined],
  [formIcon.Language, MuiIcons.LanguageOutlined],
  [formIcon.Dns, MuiIcons.DnsOutlined],
  [formIcon.Storage, MuiIcons.StorageOutlined],
  [formIcon.Schema, MuiIcons.SchemaOutlined],
  [formIcon.Inventory, MuiIcons.Inventory2Outlined],
  [formIcon.ReceiptLong, MuiIcons.ReceiptLongOutlined],
  [formIcon.Summarize, MuiIcons.SummarizeOutlined],
  [formIcon.Feed, MuiIcons.FeedOutlined],
  [formIcon.ViewList, MuiIcons.ViewListOutlined],
  [formIcon.FactCheck, MuiIcons.FactCheckOutlined],
  [formIcon.FindInPage, MuiIcons.FindInPageOutlined],
  [formIcon.UploadFile, MuiIcons.UploadFileOutlined],
  [formIcon.Download, MuiIcons.DownloadOutlined],
  [formIcon.Share, MuiIcons.ShareOutlined],
  [formIcon.Hub, MuiIcons.HubOutlined],
  [formIcon.Public, MuiIcons.PublicOutlined],
  [formIcon.Api, MuiIcons.ApiOutlined],
  [formIcon.Terminal, MuiIcons.TerminalOutlined],
  [formIcon.Database, MuiIcons.StorageOutlined],
  [formIcon.FolderShared, MuiIcons.FolderSharedOutlined],
  [formIcon.SnippetFolder, MuiIcons.SnippetFolderOutlined],
  [formIcon.Web, MuiIcons.WebOutlined],
  [formIcon.TableRows, MuiIcons.TableRowsOutlined],
  [formIcon.ViewColumn, MuiIcons.ViewColumnOutlined],
  [formIcon.ListAlt, MuiIcons.ListAltOutlined],
  [formIcon.Newspaper, MuiIcons.NewspaperOutlined],
  [formIcon.Source, MuiIcons.SourceOutlined],
  [formIcon.LibraryBooks, MuiIcons.LibraryBooksOutlined],
  [formIcon.FileCopy, MuiIcons.FileCopyOutlined],
  [formIcon.DriveFolderUpload, MuiIcons.DriveFolderUploadOutlined],
  [formIcon.CloudDone, MuiIcons.CloudDoneOutlined],
  [formIcon.Lan, MuiIcons.LanOutlined],
  [formIcon.Router, MuiIcons.RouterOutlined],
  [formIcon.AltRoute, MuiIcons.AltRouteOutlined],
  [formIcon.AccountTree, MuiIcons.AccountTreeOutlined],
  [formIcon.IntegrationInstructions, MuiIcons.IntegrationInstructionsOutlined],
  [formIcon.Code, MuiIcons.CodeOutlined],
  [formIcon.DataObject, MuiIcons.DataObjectOutlined],
  [formIcon.Backup, MuiIcons.BackupOutlined],
  [formIcon.Sync, MuiIcons.SyncOutlined],
  [formIcon.Search, MuiIcons.SearchOutlined],
  [formIcon.TravelExplore, MuiIcons.TravelExploreOutlined],
  [formIcon.TextSnippet, MuiIcons.TextSnippetOutlined],
  [formIcon.Docs, MuiIcons.ArticleOutlined],
  [formIcon.Draft, MuiIcons.DraftsOutlined],
  [formIcon.NoteAlt, MuiIcons.NoteAltOutlined],
  [formIcon.EditDocument, MuiIcons.EditNoteOutlined],
  [formIcon.InsertDriveFile, MuiIcons.InsertDriveFileOutlined],
  [formIcon.RequestPage, MuiIcons.RequestPageOutlined],
  [formIcon.Topic, MuiIcons.TopicOutlined],
  [formIcon.Reorder, MuiIcons.ReorderOutlined],
  [formIcon.ViewAgenda, MuiIcons.ViewAgendaOutlined],
  [formIcon.ViewStream, MuiIcons.ViewStreamOutlined],
  [formIcon.CalendarViewWeek, MuiIcons.CalendarViewWeekOutlined],
  [formIcon.CalendarViewMonth, MuiIcons.CalendarViewMonthOutlined],
  [formIcon.Dashboard, MuiIcons.DashboardOutlined],
  [formIcon.SpaceDashboard, MuiIcons.SpaceDashboardOutlined],
  [formIcon.Widgets, MuiIcons.WidgetsOutlined],
  [formIcon.SelectAll, MuiIcons.SelectAllOutlined],
  [formIcon.FilterList, MuiIcons.FilterListOutlined],
  [formIcon.Sort, MuiIcons.SortOutlined],
  [formIcon.Rule, MuiIcons.RuleOutlined],
  [formIcon.Checklist, MuiIcons.ChecklistOutlined],
  [formIcon.Assignment, MuiIcons.AssignmentOutlined],
  [formIcon.AssignmentTurnedIn, MuiIcons.AssignmentTurnedInOutlined],
  [formIcon.Task, MuiIcons.TaskAltOutlined],
  [formIcon.PendingActions, MuiIcons.PendingActionsOutlined],
  [formIcon.History, MuiIcons.HistoryOutlined],
  [formIcon.ManageSearch, MuiIcons.ManageSearchOutlined],
  [formIcon.SavedSearch, MuiIcons.SavedSearchOutlined],
  [formIcon.ContentPaste, MuiIcons.ContentPasteOutlined],
  [formIcon.ContentCopy, MuiIcons.ContentCopyOutlined],
  [formIcon.Archive, MuiIcons.ArchiveOutlined],
  [formIcon.Unarchive, MuiIcons.UnarchiveOutlined],
  [formIcon.FolderZip, MuiIcons.FolderZipOutlined],
  [formIcon.CreateNewFolder, MuiIcons.CreateNewFolderOutlined],
  [formIcon.FileDownloadDone, MuiIcons.FileDownloadDoneOutlined],
  [formIcon.DriveFileMove, MuiIcons.DriveFileMoveOutlined],
  [formIcon.CloudSync, MuiIcons.CloudSyncOutlined],
  [formIcon.Wifi, MuiIcons.WifiOutlined],
  [formIcon.RssFeed, MuiIcons.RssFeedOutlined],
  [formIcon.Http, MuiIcons.HttpOutlined],
  [formIcon.Cable, MuiIcons.CableOutlined],
  [formIcon.DeviceHub, MuiIcons.DeviceHubOutlined],
  [formIcon.DeveloperBoard, MuiIcons.DeveloperBoardOutlined],
  [formIcon.Memory, MuiIcons.MemoryOutlined],
  [formIcon.Monitor, MuiIcons.MonitorOutlined],
  [formIcon.DesktopWindows, MuiIcons.DesktopWindowsOutlined],
  [formIcon.OpenInBrowser, MuiIcons.OpenInBrowserOutlined],
  [formIcon.Tab, MuiIcons.TabOutlined],
  [formIcon.Polyline, MuiIcons.PolylineOutlined],
  [formIcon.MergeType, MuiIcons.MergeTypeOutlined],
  [formIcon.RocketLaunch, MuiIcons.RocketLaunchOutlined],
]);

export function getFormIconByName(iconName?: string): any {
  if (!iconName) {
    return formIconsNamesMap.get(DEFAULT_ICON_NAME);
  }

  const normalizedIconName = iconName.trim().toLowerCase();

  return formIconsNamesMap.get(normalizedIconName) ?? formIconsNamesMap.get(DEFAULT_ICON_NAME);
}
