export const texts = {
  heb: {
    emptyValue: "ערך ריק",
    listChooseRequired: "חובה לבחור פריט מהרשימה",
    addByDragAndDrop: "להוספת שדה לטופס ניתן לגרור שדה מקטלוג השדות בצד",
    duplicateInternalNames:
      "לתשומת ליבך! ישנן עמודות בטופס עם אותו שם פנימי. נדרש להגדיר שמות פנימיים שונים.",
    duplicateDisplayNames:
      "לתשומת ליבך! ישנן עמודות בטופס עם אותו שם תצוגה. נדרש להגדיר שמות תצוגה שונים.",
    missingInternalName: "לתשומת ליבך! ישנן עמודות ללא שם פנימי תקין, לכן לא ניתן לשמור.",
    missingDisplayName: "לתשומת ליבך! ישנן עמודות ללא שם תצוגה, לכן לא ניתן לשמור.",
    missingOptionName: "לתשומת ליבך! ישנן אפשרויות ללא שם, לכן לא ניתן לשמור.",
    missingFormConnection: "לתשומת ליבך! יש עמודת אפשרות שלא חיברת לטופס, לכן לא ניתן לשמור.",
    missingFieldConnection: "לתשומת ליבך! יש עמודת אפשרות שלא חיברת לשדה, לכן לא ניתן לשמור.",
    forbiddenInternalName: "לתשומת ליבך! אסור להשתמש בשם פנימי `id`, בחר שם אחר.",
    failedRetrievingResponsesCount: "שליפת כמות התגובות נכשלה",

    failedUpdatingForm: "עידכון הטופס נכשל",
    deleteForm: "מחק טופס",
    deleteFormConfirm: "האם את/ה בטוח/ה שברצונך למחוק את הטופס?",

    emptyFormAlert: "לתשומת ליבך! שם הטופס ריק",
    noHebrewTextAlert: "לתשומת ליבך! שם הטופס מורכב מאותיות שאינן עברית.",
    fiveLettersMinAlert: "לתשומת ליבך! שם הטופס פחות מ5 אותיות.",
    formNameLabel: "שם טופס",
    onlyHebrewError: "ניתן להזין רק אותיות בעברית!",
    noDescription: "ללא תיאור",
    editDetailsTooltip: "עריכת פרטי הטופס",
    savingForm: "שומר את הטופס",
    savedForm: "הטופס נשמר",
    deleteButton: "מחיקה",
    exitButton: "יציאה",
    deleteTooltip: "מחיקת הטופס",
    exitTooltip: "יציאה מהטופס",
    removeSectionAlert:
      "האם את/ה בטוח/ה שברצונך למחוק את המקטע? פעולה זו תמחק גם את כל השדות במקטע וכל התוכן המשויך אליהם לצמיתות.",
    undefinedSection: "מקטע ללא שם",
    cantRemoveLastSection: "לא ניתן למחוק את המקטע האחרון בטופס",
    emptySectionNameAlert: "לא ניתן להשאיר שם מקטע ריק",
    addSectionDescription: "הוספת תיאור מקטע",
    confirmEdit: "אישור עריכה",
    cancelEdit: "ביטול עריכה",
    editSection: "עריכת מקטע",
    expand: "הרחבת מקטע",
    collapse: "צמצום מקטע",
    deleteSection: "מחיקת מקטע",
    expandView: "תצוגה מוגדלת",
    createSectionAnnounce:
      "ניתן לחלק ולסדר את הטופס למקטעי שדות שונים, עם מאפיינים וכותרת ייעודית לכל מקטע",
    createSection: "יצירת מקטע",
    mainSection: "מקטע ראשי",
    manageConditions: "ניהול התניות",
  },
};
